package webui

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"net"
	"net/http"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/topgsmir/BackPack/internal/app"
	"github.com/topgsmir/BackPack/internal/manage"
)

// The panel's own certificate, from the panel.
//
// This is the one setting here that can lock the operator out of the page they
// are setting it from. Switching to HTTPS changes the address, restarts the
// service, and — with Let's Encrypt — depends on things outside this machine
// being right: a domain that resolves here, and a way for the CA to validate
// it. Get that wrong and the panel comes back answering TLS on a certificate it
// could never obtain, which from a browser looks exactly like the panel being
// gone.
//
// So this endpoint does not simply write what it is told. It runs the checks
// that decide whether Let's Encrypt can work, refuses the switch when they
// fail, and says which check failed. The CLI is more permissive because someone
// running it already has a shell to fix things with; whoever is using this has
// a browser and nothing else.

// certView is the current state, and everything the page needs to decide what
// to offer.
type certView struct {
	// Mode is "http", "self" or "acme" — the three the CLI offers, under the
	// same names so the two screens describe one setting.
	Mode   string `json:"mode"`
	Domain string `json:"domain,omitempty"`
	Email  string `json:"email,omitempty"`
	Port   int    `json:"port"`
	// SelfHost is the optional extra name/IP on the self-signed certificate.
	SelfHost string `json:"selfHost,omitempty"`

	// CurrentURL is where the panel answers now; NextURL is where it would
	// answer under the proposed mode. The page shows the second one before
	// anything is saved, because "the address changes" is the part people miss.
	CurrentURL string `json:"currentUrl"`

	// Expires is the current certificate's expiry, when there is one to read.
	// A self-signed certificate is generated by us and lasts years; an ACME one
	// renews itself. Shown because an expired certificate and a broken panel
	// look the same from outside.
	Expires string `json:"expires,omitempty"`
	// ExpiresDays is negative once it has expired.
	ExpiresDays int `json:"expiresDays,omitempty"`

	// What Let's Encrypt would need. Reported whether or not it is selected, so
	// the page can grey out an option that cannot work here and say why rather
	// than letting it be chosen and fail after the restart.
	PublicIP   string `json:"publicIp,omitempty"`
	Port80Free bool   `json:"port80Free"`
	// ACMEPath explains how validation would happen: "alpn" when the panel is
	// on 443 and the listener can answer for itself, "http01" when port 80 is
	// free, or "" when neither is available.
	// CertFile and KeyFile are the operator's own certificate, in "own" mode,
	// and Names what it covers.
	CertFile string   `json:"certFile,omitempty"`
	KeyFile  string   `json:"keyFile,omitempty"`
	Names    []string `json:"names,omitempty"`

	ACMEPath string `json:"acmePath"`
	ACMENote string `json:"acmeNote,omitempty"`
}

func (s *server) handlePanelCert(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		writeJSON(w, certSnapshot())
	case http.MethodPost:
		s.applyPanelCert(w, r)
	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}

func certSnapshot() certView {
	c := Load()

	v := certView{Mode: "http", Domain: c.TLSDomain, Email: c.TLSEmail, Port: c.Port, SelfHost: c.TLSSelfHost}
	switch {
	case !c.HTTPS:
		v.Mode = "http"
	case c.OwnCert():
		v.Mode = "own"
		v.CertFile, v.KeyFile = c.TLSCertFile, c.TLSKeyFile
		if names, notAfter, err := CheckOwnCert(c.TLSCertFile, c.TLSKeyFile); err == nil {
			v.Names = names
			v.Expires = notAfter.Format("2006-01-02")
			v.ExpiresDays = int(time.Until(notAfter).Hours() / 24)
		}
	case c.TLSDomain != "":
		v.Mode = "acme"
	default:
		v.Mode = "self"
	}

	host := c.TLSDomain
	if host == "" {
		host = manage.PublicIPv4()
	}
	v.PublicIP = manage.PublicIPv4()
	v.CurrentURL = panelURL(c.Scheme(), host, c.Port)

	// Only the self-signed certificate is a file we can read. An ACME one lives
	// in autocert's cache in a format that is its business, and it renews
	// itself, so there is nothing useful to say about its expiry here.
	if v.Mode == "self" {
		if certFile, _, err := manage.EnsurePanelCert(c.TLSSelfHost); err == nil {
			if notAfter, err := manage.CertExpiry(certFile); err == nil {
				v.Expires = notAfter.Format("2006-01-02")
				v.ExpiresDays = int(time.Until(notAfter).Hours() / 24)
			}
		}
	}

	v.Port80Free = !manage.PortInUse("80")
	v.ACMEPath, v.ACMENote = acmeValidationPath(c.Port, v.Port80Free)
	return v
}

// acmeValidationPath reports how Let's Encrypt could validate this server, and
// says so in the terms the operator can act on.
//
// There are exactly two routes. On port 443 the panel's own listener answers
// the challenge over TLS-ALPN, needing nothing else open. Anywhere else — and
// the panel's default is 7777 — the challenge has to arrive over plain HTTP on
// port 80, so that port must be free for the responder to bind.
func acmeValidationPath(panelPort int, port80Free bool) (string, string) {
	if panelPort == 443 {
		return "alpn", "The panel is on 443, so it can answer the challenge itself."
	}
	if port80Free {
		return "http01", "Port 80 is free — Let's Encrypt will use it to verify the domain."
	}
	return "", "Port 80 is in use and the panel is not on 443, so there is no way for " +
		"Let's Encrypt to verify the domain. Free port 80, or move the panel to 443."
}

func panelURL(scheme, host string, port int) string {
	if host == "" {
		host = "<server-ip>"
	}
	// A bare IPv6 address needs brackets before a port can be appended.
	if strings.Count(host, ":") >= 2 {
		host = "[" + host + "]"
	}
	if (scheme == "http" && port == 80) || (scheme == "https" && port == 443) {
		return scheme + "://" + host + "/"
	}
	return scheme + "://" + host + ":" + strconv.Itoa(port) + "/"
}

func (s *server) applyPanelCert(w http.ResponseWriter, r *http.Request) {
	if err := r.ParseForm(); err != nil {
		http.Error(w, "could not read the form", http.StatusBadRequest)
		return
	}
	mode := strings.TrimSpace(r.FormValue("mode"))
	domain := strings.ToLower(strings.TrimSpace(r.FormValue("domain")))
	email := strings.TrimSpace(r.FormValue("email"))

	c := Load()
	next := c

	// Every mode but "own" forgets a brought certificate; "own" sets it.
	next.TLSCertFile, next.TLSKeyFile = "", ""

	switch mode {
	case "http":
		next.HTTPS, next.TLSDomain, next.TLSEmail, next.TLSSelfHost = false, "", "", ""
	case "own":
		certFile := strings.TrimSpace(r.FormValue("certFile"))
		keyFile := strings.TrimSpace(r.FormValue("keyFile"))
		if _, _, err := CheckOwnCert(certFile, keyFile); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		next.HTTPS, next.TLSDomain, next.TLSEmail, next.TLSSelfHost = true, "", "", ""
		next.TLSCertFile, next.TLSKeyFile = certFile, keyFile
	case "self":
		// The domain field is optional for self-signed: an extra SAN, not a
		// requirement. An IP typed here is fine too. Every local address is
		// covered regardless.
		if domain != "" && net.ParseIP(domain) == nil && !validHostname(domain) {
			http.Error(w, fmt.Sprintf("%q is not a valid domain or IP", domain), http.StatusBadRequest)
			return
		}
		next.HTTPS, next.TLSDomain, next.TLSEmail, next.TLSSelfHost = true, "", "", domain
	case "acme":
		if err := validateACME(domain, c.Port); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		next.HTTPS, next.TLSDomain, next.TLSEmail, next.TLSSelfHost = true, domain, email, ""
	default:
		http.Error(w, "unknown mode", http.StatusBadRequest)
		return
	}

	host := next.TLSDomain
	if host == "" {
		host = next.TLSSelfHost
	}
	if host == "" || host == "-" {
		host = manage.PublicIPv4()
	}
	if host == "-" {
		host = "" // panelURL renders the placeholder rather than a bare dash
	}
	url := panelURL(next.Scheme(), host, next.Port)

	if next.Equal(c) {
		writeJSON(w, map[string]any{"status": "unchanged", "url": url})
		return
	}

	// A self-signed certificate is generated here rather than on the way up, so
	// a failure is reported into this response — where someone is looking —
	// instead of into a log after the panel has already restarted onto a
	// listener that cannot complete a handshake.
	if next.HTTPS && next.TLSDomain == "" && !next.OwnCert() {
		if _, _, err := manage.EnsurePanelCert(next.TLSSelfHost); err != nil {
			http.Error(w, "could not generate a certificate: "+err.Error(),
				http.StatusInternalServerError)
			return
		}
	}

	if err := Save(next); err != nil {
		http.Error(w, "could not save the configuration", http.StatusInternalServerError)
		return
	}

	// Answer before restarting: the restart kills this connection, and the page
	// needs the new address in order to send the browser there.
	writeJSON(w, map[string]any{
		"status": "ok",
		"url":    url,
		"mode":   mode,
		// The browser will refuse a self-signed certificate until someone
		// accepts it by hand, and a page that redirects into that warning with
		// no explanation reads as the panel having broken.
		"warns":  next.HTTPS && next.TLSDomain == "" && !next.OwnCert(),
		"issues": mode == "acme",
	})
	go func() {
		time.Sleep(500 * time.Millisecond)
		manage.RestartService(app.WebUIService)
	}()
}

// validateACME runs the checks that decide whether Let's Encrypt can succeed.
//
// Every one of these failing means the same thing in practice: the panel
// restarts, cannot obtain a certificate, and answers nothing a browser will
// talk to. Catching them here costs a few seconds; not catching them costs the
// operator their only way in.
func validateACME(domain string, panelPort int) error {
	if domain == "" {
		return fmt.Errorf("a domain is required for Let's Encrypt")
	}
	// Before the general check, because typing the server's own address here is
	// the likely mistake and "not a valid domain name" would not explain it.
	if net.ParseIP(domain) != nil {
		return fmt.Errorf("Let's Encrypt cannot issue a certificate for an IP address — " +
			"use a domain, or choose the self-signed option, which works on a bare IP")
	}
	if !validHostname(domain) {
		return fmt.Errorf("%q is not a valid domain name", domain)
	}

	if path, note := acmeValidationPath(panelPort, !manage.PortInUse("80")); path == "" {
		return fmt.Errorf("%s", note)
	}

	// The domain has to point here, or the CA will validate somebody else's
	// server and hand back nothing.
	ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
	defer cancel()
	addrs, err := net.DefaultResolver.LookupHost(ctx, domain)
	if err != nil || len(addrs) == 0 {
		return fmt.Errorf("%s does not resolve — point it at this server first, "+
			"and allow time for DNS to propagate", domain)
	}
	mine := map[string]bool{}
	for _, ip := range []string{manage.PublicIPv4(), manage.PublicIPv6()} {
		if ip != "" && ip != "-" {
			mine[ip] = true
		}
	}
	// When this server's own public address could not be determined there is
	// nothing to compare against. Refusing on that basis would block a setup
	// that is very likely fine, so the DNS answer alone is accepted.
	if len(mine) == 0 {
		return nil
	}
	for _, a := range addrs {
		if mine[a] {
			return nil
		}
	}
	return fmt.Errorf("%s resolves to %s, which is not this server (%s) — "+
		"Let's Encrypt would fail and the panel would be unreachable",
		domain, strings.Join(addrs, ", "), strings.Join(keys(mine), ", "))
}

func keys(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	return out
}

// validHostname is a deliberately plain check: labels of letters, digits and
// hyphens, separated by dots, with a real TLD. It is not trying to be the RFC;
// it is trying to catch a typo before it costs a restart.
func validHostname(h string) bool {
	if len(h) > 253 || !strings.Contains(h, ".") || strings.HasSuffix(h, ".") {
		return false
	}
	for _, label := range strings.Split(h, ".") {
		if len(label) == 0 || len(label) > 63 {
			return false
		}
		if label[0] == '-' || label[len(label)-1] == '-' {
			return false
		}
		for i := 0; i < len(label); i++ {
			ch := label[i]
			ok := (ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9') || ch == '-'
			if !ok {
				return false
			}
		}
	}
	// The last label must not be all digits, which is how an IPv4 address
	// sneaks past the rest of this.
	last := h[strings.LastIndex(h, ".")+1:]
	for i := 0; i < len(last); i++ {
		if last[i] < '0' || last[i] > '9' {
			return true
		}
	}
	return false
}

// CheckOwnCert refuses a brought certificate the panel could not serve: files
// that cannot be read, a key that is not the certificate's, a certificate that
// has already expired. Said now, while the operator is at the form, rather
// than as a panel that does not come back after the restart.
//
// It reports what the certificate names, so the screen can show whether it
// covers the address the panel is reached on.
func CheckOwnCert(certFile, keyFile string) (names []string, notAfter time.Time, err error) {
	if certFile == "" || keyFile == "" {
		return nil, time.Time{}, fmt.Errorf("give both files: the certificate (certbot's " +
			"fullchain.pem) and its private key (privkey.pem)")
	}
	if !filepath.IsAbs(certFile) || !filepath.IsAbs(keyFile) {
		return nil, time.Time{}, fmt.Errorf("give full paths, starting with /")
	}
	pair, err := tls.LoadX509KeyPair(certFile, keyFile)
	if err != nil {
		return nil, time.Time{}, fmt.Errorf("the certificate and key cannot be used together: %v "+
			"— they must be PEM files, the certificate first in its file, and the key must be "+
			"the one the certificate was issued for", err)
	}
	leaf, err := x509.ParseCertificate(pair.Certificate[0])
	if err != nil {
		return nil, time.Time{}, fmt.Errorf("the certificate cannot be read: %v", err)
	}
	if time.Now().After(leaf.NotAfter) {
		return nil, time.Time{}, fmt.Errorf("the certificate expired on %s",
			leaf.NotAfter.Format("2006-01-02"))
	}
	names = append(names, leaf.DNSNames...)
	for _, ip := range leaf.IPAddresses {
		names = append(names, ip.String())
	}
	return names, leaf.NotAfter, nil
}
