// Command configref generates the configuration reference from the struct tags.
//
// Every `toml:` key in config/ is documented in prose across docs/, and a test
// already proves each one is *wired* to code that acts on it. Nothing proved
// the prose still described it. A key renamed, retyped or moved between
// sections leaves the documentation confidently wrong, and wrong documentation
// about a configuration file is worse than none: an operator copies it.
//
// So the reference is generated from the declarations themselves, and the
// comment above each field — which this codebase already writes carefully — is
// the description. There is nothing to keep in sync because there is one copy.
//
//	go run ./tools/configref > docs/config-reference.md
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

type field struct {
	Key     string
	Type    string
	Doc     string
	Section string
	File    string
}

func main() {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, "config", nil, parser.ParseComments)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parsing config/: %v\n", err)
		os.Exit(1)
	}

	var fields []field
	for _, pkg := range pkgs {
		for path, file := range pkg.Files {
			ast.Inspect(file, func(n ast.Node) bool {
				ts, ok := n.(*ast.TypeSpec)
				if !ok {
					return true
				}
				st, ok := ts.Type.(*ast.StructType)
				if !ok {
					return true
				}
				for _, f := range st.Fields.List {
					key := tomlKey(f)
					if key == "" {
						continue
					}
					fields = append(fields, field{
						Key:     key,
						Type:    typeName(f.Type),
						Doc:     docOf(f),
						Section: sectionOf(ts.Name.Name),
						File:    filepath.Base(path),
					})
				}
				return true
			})
		}
	}

	sort.Slice(fields, func(i, j int) bool {
		if fields[i].Section != fields[j].Section {
			return fields[i].Section < fields[j].Section
		}
		return fields[i].Key < fields[j].Key
	})

	write(fields)
}

// tomlKey pulls the key out of a field's tag, or "" when it has none.
func tomlKey(f *ast.Field) string {
	if f.Tag == nil {
		return ""
	}
	tag := strings.Trim(f.Tag.Value, "`")
	i := strings.Index(tag, `toml:"`)
	if i < 0 {
		return ""
	}
	rest := tag[i+len(`toml:"`):]
	j := strings.Index(rest, `"`)
	if j < 0 {
		return ""
	}
	key := rest[:j]
	if c := strings.Index(key, ","); c >= 0 {
		key = key[:c]
	}
	if key == "" || key == "-" {
		return ""
	}
	return key
}

func typeName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.ArrayType:
		return "[]" + typeName(t.Elt)
	case *ast.SelectorExpr:
		return typeName(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + typeName(t.X)
	case *ast.MapType:
		return "map[" + typeName(t.Key) + "]" + typeName(t.Value)
	}
	return "?"
}

// docOf is the comment above the field, which is where this codebase already
// keeps the explanation. Only the first paragraph: the rest is usually the
// history of why it is the way it is, which belongs in the source and not in a
// reference table.
func docOf(f *ast.Field) string {
	if f.Doc == nil {
		return ""
	}
	var lines []string
	for _, c := range f.Doc.List {
		t := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if t == "" {
			break
		}
		lines = append(lines, t)
	}
	return strings.Join(lines, " ")
}

// sectionOf maps a struct to the TOML table it appears under.
func sectionOf(name string) string {
	switch name {
	case "ServerConfig":
		return "[server]"
	case "ClientConfig":
		return "[client]"
	case "DirectConfig":
		return "[direct]"
	case "L3Config":
		return "[l3]"
	case "SpoofConfig":
		return "[l3] — the spoof carrier"
	case "KCPConfig":
		return "KCP tuning"
	}
	return name
}

func write(fields []field) {
	out := os.Stdout
	fmt.Fprint(out, "# Configuration reference\n\n"+
		"Every key bk reads, generated from the declarations in `config/` so it\n"+
		"cannot drift from them.\n\n"+
		"**Do not edit this file.** Regenerate it:\n\n"+
		"```\ngo run ./tools/configref > docs/config-reference.md\n```\n\n"+
		"The prose pages under `docs/` explain what to *use* these for and which of\n"+
		"them both ends have to agree on. This says what exists.\n")

	section := ""
	for _, f := range fields {
		if f.Section != section {
			section = f.Section
			fmt.Fprintf(out, "\n## %s\n\n| Key | Type | Description |\n|---|---|---|\n", section)
		}
		doc := f.Doc
		if doc == "" {
			doc = "_(undocumented — add a comment above the field in `config/" + f.File + "`)_"
		}
		doc = strings.ReplaceAll(doc, "|", "\\|")
		fmt.Fprintf(out, "| `%s` | `%s` | %s |\n", f.Key, f.Type, doc)
	}

	// The Persian note is generated with the table rather than written beside
	// it, because this file is overwritten every time the declarations change
	// and anything hand-added to it is lost on the next regeneration.
	//
	// It is a note rather than a translation: the keys are English identifiers
	// and the descriptions come from the Go comments above them, so translating
	// the table would mean translating the source of truth and letting the two
	// drift. What a Persian reader needs from this page is what it is, where it
	// comes from, and which page to read instead for the reasoning.
	fmt.Fprint(out, "\n---\n\n<div dir=\"rtl\">\n\n## خلاصهٔ فارسی\n\n"+
		"هر کلیدی که bk می‌خواند، **تولیدشده از روی خودِ اعلان‌ها در `config/`**\n"+
		"تا نتواند از آن‌ها جدا بیفتد. توضیح هر کلید همان کامنت بالای همان فیلد در\n"+
		"سورس است.\n\n"+
		"**این فایل را دستی ویرایش نکن** — با `go run ./tools/configref > docs/config-reference.md`\n"+
		"دوباره ساخته می‌شود و هر چیزی که دستی اضافه شده باشد از بین می‌رود.\n\n"+
		"این صفحه می‌گوید **چه چیزی وجود دارد**. اینکه هر کدام به چه درد می‌خورند و\n"+
		"کدام‌هایشان باید روی هر دو سر یکی باشند، در صفحه‌های نثرِ زیر `docs/` توضیح\n"+
		"داده شده — مخصوصاً [transports](transports.md)،\n"+
		"[port-mappings](port-mappings.md)، [mss-clamp](mss-clamp.md) و\n"+
		"[performance-presets](performance-presets.md).\n\n"+
		"</div>\n")

	fmt.Fprintf(out, "\n---\n\n*Generated from `config/` on %s. Last verified against bk %s.*\n",
		time.Now().Format("2006-01-02"), version())
}

func version() string {
	b, err := os.ReadFile("VERSION")
	if err != nil {
		return "(unknown)"
	}
	return strings.TrimSpace(string(b))
}
